- name: Set configuration values for django application
  hosts: django_app
  gather_facts: false
  become: true

  tasks:
    - name: copy secret config settings
      copy:
        src: "../../config/{{ env }}/config.json"
        dest: /etc/config.json
   
    - name: copy django settings file
      template:
        src: "../../config/{{ env }}/settings.py.j2"
        dest: /home/{{ deploy_user }}/{{ project_name }}/source/{{ project_name }}/settings.py
