name: Django CI/CD Deployment

on:
  push:
    branches: [master, hotfix-*]
  release:
    types: [published]

jobs:
  build:
    name: Build and test webapp
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/requirements.txt

      - name: Run Tests
        run: |
          python source/manage.py test

      - name: Package files
        run: tar -czf application.tar.gz source/ scripts/ ansible/ config/

      - name: Upload application artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.run_id }}
          path: application.tar.gz

  deploy_staging_source:
    name: Deploy source to staging
    needs: [build, deploy_staging_config]
    runs-on: ubuntu-latest
    concurrency: staging
    if: ${{ github.event_name == 'release' || github.ref == 'refs/heads/master' }}

    steps:
      - name: Install ansible
        run: sudo apt-get install ansible

      - name: Download application artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.run_id }}
          path: .

      - name: Unpack files
        run: tar -xzf application.tar.gz

      - name: Package source
        run: tar -czf source.tar.gz source/

      - name: Write secret files
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          SSH_KEY: ${{ secrets.GZP_GH_KEY }}
        run: echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt && echo "$SSH_KEY" > ssh_key && chmod 400 ssh_key

      - name: Deploy source
        env:
          SSH_KEY_FILE: ssh_key
          VAULT_PW_FILE: vault_pass.txt
          ENV: staging
          DOMAIN: ${{ secrets.STG_DOMAIN }}
        run: ./scripts/deploy_app.sh

  deploy_staging_config:
    name: Deploy config to staging
    needs: [build]
    runs-on: ubuntu-latest
    concurrency: staging
    if: ${{ github.event_name == 'release' || github.ref == 'refs/heads/master' }}

    steps:
      - name: Install ansible
        run: sudo apt-get install ansible

      - name: Download application artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.run_id }}
          path: .

      - name: Unpack files
        run: tar -xzf application.tar.gz

      - name: Write secret files
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          SSH_KEY: ${{ secrets.GZP_GH_KEY }}
        run: echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt && echo "$SSH_KEY" > ssh_key && chmod 400 ssh_key

      - name: Deploy config
        env:
          SSH_KEY_FILE: ssh_key
          VAULT_PW_FILE: vault_pass.txt
          ENV: staging
        run: ./scripts/deploy_config.sh

  deploy_production_source:
    name: Deploy source to production
    needs: [smoke_test_staging, deploy_production_config]
    runs-on: ubuntu-latest
    concurrency: production
    if: ${{ github.event_name == 'release'}}

    steps:
      - name: Install ansible
        run: sudo apt-get install ansible

      - name: Download application artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.run_id }}
          path: .

      - name: Unpack files
        run: tar -xzf application.tar.gz

      - name: Package source
        run: tar -czf source.tar.gz source/

      - name: Write secret files
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          SSH_KEY: ${{ secrets.GZP_GH_KEY }}
        run: echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt && echo "$SSH_KEY" > ssh_key && chmod 400 ssh_key

      - name: Deploy source
        env:
          SSH_KEY_FILE: ssh_key
          VAULT_PW_FILE: vault_pass.txt
          ENV: production
          DOMAIN: ${{ secrets.PRD_DOMAIN }}
        run: ./scripts/deploy_app.sh

  deploy_production_config:
    name: Deploy config to production
    needs: [smoke_test_staging]
    runs-on: ubuntu-latest
    concurrency: production
    if: ${{ github.event_name == 'release' || github.ref == 'refs/heads/master' }}

    steps:
      - name: Install ansible
        run: sudo apt-get install ansible

      - name: Download application artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.run_id }}
          path: .

      - name: Unpack files
        run: tar -xzf application.tar.gz

      - name: Write secret files
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          SSH_KEY: ${{ secrets.GZP_GH_KEY }}
        run: echo "$ANSIBLE_VAULT_PASSWORD" > vault_pass.txt && echo "$SSH_KEY" > ssh_key && chmod 400 ssh_key

      - name: Deploy config
        env:
          SSH_KEY_FILE: ssh_key
          VAULT_PW_FILE: vault_pass.txt
          ENV: production
        run: ./scripts/deploy_config.sh

  smoke_test_staging:
    name: Smoke test webapp staging
    needs: [deploy_staging_source, deploy_staging_config]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Liveness check
        run: HTTP_STATUS_OK=200 STATUS=$(curl -L --head --silent --write-out '%{http_code}' --output /dev/null ${{ secrets.STG_DOMAIN }}) test $HTTP_STATUS_OK = $STATUS
     
  smoke_test_production:
    name: Smoke test webapp production
    needs: [deploy_production_source, deploy_production_config]
    runs-on: ubuntu-latest
    if: always()

    steps:     
      - name: Liveness check
        run: HTTP_STATUS_OK=200 STATUS=$(curl -L --head --silent --write-out '%{http_code}' --output /dev/null ${{ secrets.PRD_DOMAIN }}) test $HTTP_STATUS_OK = $STATUS
